---
openapi: 3.0.1
info:
  title: Operate Public API
  description:
    To access active and completed process instances in Operate for monitoring
    and troubleshooting
  contact:
    url: https://www.camunda.com
  license:
    name: License
    url: https://docs.camunda.io/docs/reference/licenses/
  version: 1.0.0
servers:
  - url: "https://{SERVER_URL}"
    description: Generated server url
tags:
  - name: ProcessInstance
    description: Process instance API
  - name: ProcessDefinition
    description: Process definition API
  - name: Flownode-instance
    description: Flownode Instances API
  - name: Variable
    description: Variable API
  - name: Incident
    description: Incident API
paths:
  "/v1/variables/search":
    post:
      tags:
        - Variable
      summary: Search variables for process instances
      operationId: search
      requestBody:
        description: Search variables
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryVariable"
            examples:
              All:
                description: Returns all variables (default return list size is 10)
                value: {}
              Size:
                description: "Returns 20 variables "
                value:
                  size: 20
              Filter and sort:
                description:
                  Returns all variables with 'processInstanceKey' '9007199254741196'
                  sorted ascending by name
                value:
                  filter:
                    processInstanceKey: "9007199254741196"
                  sort:
                    - field: name
                      order: ASC
              Paging:
                description:
                  "Returns next variables for 'processInstanceKey' ascending
                  by 'name'. (Copy value of 'sortValues' field of previous results) "
                value:
                  filter:
                    processInstanceKey: "9007199254741196"
                  sort:
                    - field: name
                      order: ASC
                  searchAfter:
                    - small
                    - 9007199254741200
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResultsVariable"
        "400":
          description: Data invalid
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
  "/v1/process-instances/search":
    post:
      tags:
        - ProcessInstance
      summary: Search process instances
      operationId: search_1
      requestBody:
        description: Search process instances
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryProcessInstance"
            examples:
              All:
                description:
                  Returns all process instances (default return list size
                  is 10)
                value: {}
              Sorted by field:
                description: Returns process instances sorted ascending by bpmnProcessId
                value:
                  sort:
                    - field: bpmnProcessId
                      order: ASC
              Sorted and paged with size:
                description:
                  "Returns max 3 process instances after 'bigVarProcess'
                  and key 6755399441055870 sorted ascending by bpmnProcessId \nTo
                  get the next page copy the value of 'sortValues' into 'searchAfter'
                  value.\nSort specification should match the searchAfter specification"
                value:
                  size: 3
                  sort:
                    - field: bpmnProcessId
                      order: ASC
                  searchAfter:
                    - bigVarProcess
                    - 6755399441055870
              Filtered and sorted:
                description:
                  Returns max 50 process instances, filtered by processVersion
                  of 2 sorted ascending by bpmnProcessId
                value:
                  filter:
                    processVersion: 2
                  size: 50
                  sort:
                    - field: bpmnProcessId
                      order: ASC
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResultsProcessInstance"
        "400":
          description: Data invalid
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
  "/v1/process-definitions/search":
    post:
      tags:
        - ProcessDefinition
      summary: Search process definitions
      operationId: search_2
      requestBody:
        description: Search examples
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryProcessDefinition"
            examples:
              All:
                description: All process instances (default size is 10)
                value: {}
              Size of returned list:
                description: Search process instances and return list of size 5
                value:
                  size: 5
              Sort:
                description: Search process instances and sort by name
                value:
                  sort:
                    - field: name
                      order: ASC
              Sort and size:
                description:
                  Search process instances, sort descending by name list
                  size of 5
                value:
                  size: 5
                  sort:
                    - field: name
                      order: DESC
              Sort and page:
                description:
                  "Search process instances,sort by name and page results
                  of size 5. \n To get the next page copy the value of 'sortValues'
                  into 'searchAfter' value.\nSort specification should match the searchAfter
                  specification"
                value:
                  size: 5
                  sort:
                    - field: name
                      order: ASC
                  searchAfter:
                    - Called Process
                    - "2251799813687281"
              "Filter and sort ":
                description: Filter by version and sort by bpmnProcessId
                value:
                  filter:
                    version: 1
                  size: 50
                  sort:
                    - field: bpmnProcessId
                      order: ASC
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResultsProcessDefinition"
        "400":
          description: Data invalid
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
  "/v1/incidents/search":
    post:
      tags:
        - Incident
      summary: Search incidents
      operationId: search_3
      requestBody:
        description: Search incidents
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryIncident"
            examples:
              All:
                description: Returns all incidents (default return list size is 10).
                value: {}
              Return 20 items:
                description: Returns max 20 incidents.
                value:
                  size: 20
              Sort by field:
                description: Returns incidents sorted descending by 'creationTime'
                value:
                  sort:
                    - field: creationTime
                      order: DESC
              Filter by field:
                description:
                  Returns incidents filtered by 'type'. Field 'message'
                  can't be used for filter and sort
                value:
                  filter:
                    type: UNHANDLED_ERROR_EVENT
              Filter and sort:
                description:
                  Filter by 'type' and 'processDefinitionKey', sorted descending
                  by 'creationTime'.
                value:
                  filter:
                    type: CALLED_ELEMENT_ERROR
                    processDefinitionKey: "2251799813686167"
                  sort:
                    - field: creationTime
                      order: DESC
              Page by key:
                description:
                  Returns paged by using previous returned 'sortValues'
                  value (array).
                value:
                  searchAfter:
                    - 2251799813687785
              Filter, sort and page:
                description:
                  Returns incidents filtered by 'type' and 'processDefinitionKey',
                  sorted descending by 'creationTime' and paged from previous 'sortValues'
                  value.
                value:
                  filter:
                    type: CALLED_ELEMENT_ERROR
                    processDefinitionKey: "2251799813686167"
                  sort:
                    - field: creationTime
                      order: DESC
                  searchAfter:
                    - 1646904085499
                    - 9007199254743288
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResultsIncident"
        "400":
          description: Data invalid
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
  "/v1/flownode-instances/search":
    post:
      tags:
        - Flownode-instance
      summary: Search flownode-instances
      operationId: search_4
      requestBody:
        description: Search flownode-instances
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryFlowNodeInstance"
            examples:
              All:
                description:
                  Returns all flownode instances (default return list size
                  is 10).
                value: {}
              Return 20 items:
                description: Returns max 20 incidents.
                value:
                  size: 20
              Sort by field:
                description: Returns flownode instances sorted descending by 'endDate'
                value:
                  sort:
                    - field: endDate
                      order: DESC
              Filter by field:
                description: Returns flownode instances filtered by 'incident'.
                value:
                  filter:
                    incident: true
              Filter and sort:
                description: Filter by 'incident' , sorted descending by 'startDate'.
                value:
                  filter:
                    incident: true
                  sort:
                    - field: startDate
                      order: DESC
              Page by key:
                description:
                  Returns paged by using previous returned 'sortValues'
                  value (array). Choose an existing key from previous searches to
                  try this.
                value:
                  searchAfter:
                    - 2251799813687785
              Filter, sort and page:
                description:
                  Returns flownode instances filtered by 'incident' , sorted
                  ascending by 'startDate' and paged from previous 'sortValues' value.
                value:
                  filter:
                    incident: true
                  sort:
                    - field: startDate
                      order: ASC
                  searchAfter:
                    - 1646904085499
                    - 9007199254743288
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResultsFlowNodeInstance"
        "400":
          description: Data invalid
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
  "/v1/variables/{key}":
    get:
      tags:
        - Variable
      summary: Get variable by key
      operationId: byKey
      parameters:
        - name: key
          in: path
          description: Key of variable
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Variable"
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Requested resource not found
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
  "/v1/process-instances/{key}":
    get:
      tags:
        - ProcessInstance
      summary: Get process instance by key
      operationId: byKey_1
      parameters:
        - name: key
          in: path
          description: Key of process instance
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ProcessInstance"
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Requested resource not found
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
    delete:
      tags:
        - ProcessInstance
      summary: Delete process instance and all dependant data by key
      operationId: delete
      parameters:
        - name: key
          in: path
          description: Key of process instance
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ChangeStatus"
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Requested resource not found
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
  "/v1/process-definitions/{key}":
    get:
      tags:
        - Process
        - ProcessDefinition
      summary: Get process definition by key
      operationId: byKey_2
      parameters:
        - name: key
          in: path
          description: Key of process definition
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ProcessDefinition"
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Requested resource not found
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
  "/v1/process-definitions/{key}/xml":
    get:
      tags:
        - Process
        - ProcessDefinition
      summary: Get process definition as XML by key
      operationId: xmlByKey
      parameters:
        - name: key
          in: path
          description: Key of process definition
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            text/xml:
              schema:
                type: string
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Requested resource not found
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
  "/v1/incidents/{key}":
    get:
      tags:
        - Incident
      summary: Get incident by key
      operationId: byKey_3
      parameters:
        - name: key
          in: path
          description: Key of process instance
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Incident"
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Requested resource not found
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
  "/v1/flownode-instances/{key}":
    get:
      tags:
        - Flownode-instance
      summary: Get flow node instance by key
      operationId: byKey_4
      parameters:
        - name: key
          in: path
          description: Key of flownode instance
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/FlowNodeInstance"
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Error"
        "404":
          description: Requested resource not found
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
        "500":
          description: API application error
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/Error"
      security:
        - bearer-key: []
        - cookie: []
components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
        instance:
          type: string
        type:
          type: string
    QueryVariable:
      type: object
      properties:
        filter:
          "$ref": "#/components/schemas/Variable"
        size:
          type: integer
          format: int32
        searchAfter:
          type: array
          items:
            type: object
        sort:
          type: array
          items:
            "$ref": "#/components/schemas/Sort"
    Sort:
      type: object
      properties:
        field:
          type: string
        order:
          type: string
          enum:
            - ASC
            - DESC
    Variable:
      type: object
      properties:
        key:
          type: integer
          format: int64
        processInstanceKey:
          type: integer
          format: int64
        scopeKey:
          type: integer
          format: int64
        name:
          type: string
        value:
          type: string
        truncated:
          type: boolean
    ResultsVariable:
      type: object
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/Variable"
        sortValues:
          type: array
          items:
            type: object
        total:
          type: integer
          format: int64
    ProcessInstance:
      type: object
      properties:
        key:
          type: integer
          format: int64
        processVersion:
          type: integer
          format: int32
        bpmnProcessId:
          type: string
        parentKey:
          type: integer
          format: int64
        startDate:
          type: string
        endDate:
          type: string
        state:
          type: string
        processDefinitionKey:
          type: integer
          format: int64
    QueryProcessInstance:
      type: object
      properties:
        filter:
          "$ref": "#/components/schemas/ProcessInstance"
        size:
          type: integer
          format: int32
        searchAfter:
          type: array
          items:
            type: object
        sort:
          type: array
          items:
            "$ref": "#/components/schemas/Sort"
    ResultsProcessInstance:
      type: object
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/ProcessInstance"
        sortValues:
          type: array
          items:
            type: object
        total:
          type: integer
          format: int64
    ProcessDefinition:
      type: object
      properties:
        key:
          type: integer
          format: int64
        name:
          type: string
        version:
          type: integer
          format: int32
        bpmnProcessId:
          type: string
    QueryProcessDefinition:
      type: object
      properties:
        filter:
          "$ref": "#/components/schemas/ProcessDefinition"
        size:
          type: integer
          format: int32
        searchAfter:
          type: array
          items:
            type: object
        sort:
          type: array
          items:
            "$ref": "#/components/schemas/Sort"
    ResultsProcessDefinition:
      type: object
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/ProcessDefinition"
        sortValues:
          type: array
          items:
            type: object
        total:
          type: integer
          format: int64
    Incident:
      type: object
      properties:
        key:
          type: integer
          format: int64
        processDefinitionKey:
          type: integer
          format: int64
        processInstanceKey:
          type: integer
          format: int64
        type:
          type: string
        message:
          type: string
        creationTime:
          type: string
        state:
          type: string
    QueryIncident:
      type: object
      properties:
        filter:
          "$ref": "#/components/schemas/Incident"
        size:
          type: integer
          format: int32
        searchAfter:
          type: array
          items:
            type: object
        sort:
          type: array
          items:
            "$ref": "#/components/schemas/Sort"
    ResultsIncident:
      type: object
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/Incident"
        sortValues:
          type: array
          items:
            type: object
        total:
          type: integer
          format: int64
    FlowNodeInstance:
      type: object
      properties:
        key:
          type: integer
          format: int64
        processInstanceKey:
          type: integer
          format: int64
        startDate:
          type: string
        endDate:
          type: string
        incidentKey:
          type: integer
          format: int64
        type:
          type: string
        state:
          type: string
        incident:
          type: boolean
    QueryFlowNodeInstance:
      type: object
      properties:
        filter:
          "$ref": "#/components/schemas/FlowNodeInstance"
        size:
          type: integer
          format: int32
        searchAfter:
          type: array
          items:
            type: object
        sort:
          type: array
          items:
            "$ref": "#/components/schemas/Sort"
    ResultsFlowNodeInstance:
      type: object
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/FlowNodeInstance"
        sortValues:
          type: array
          items:
            type: object
        total:
          type: integer
          format: int64
    ChangeStatus:
      type: object
      properties:
        message:
          type: string
        deleted:
          type: integer
          format: int64
  securitySchemes:
    cookie:
      type: apiKey
      name: OPERATE-SESSION
      in: cookie
    bearer-key:
      type: http
      scheme: bearer
      bearerFormat: JWT
